# Generated by Django 5.2.17 on 2026-09-21 13:47

from django.db import migrations, models


def split_existing_names(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all().iterator():
        parts = user.full_name.strip().split(maxsplit=1)
        user.first_name = parts[0] if parts else "Member"
        user.last_name = parts[1] if len(parts) > 1 else ""
        user.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_display_name_user_full_name_activitylog'),
    ]

    operations = [
        migrations.RunPython(split_existing_names, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
