# Generated by Django 5.2.17 on 2026-09-21 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='betslip_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='commences_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(default='Accumulator', max_length=80),
        ),
        migrations.AddField(
            model_name='package',
            name='win_probability',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
