# Generated by Django 5.2.17 on 2026-09-21 17:07

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from uuid import uuid4


def create_existing_payments(apps, schema_editor):
    Subscription = apps.get_model('catalog', 'Subscription')
    Payment = apps.get_model('catalog', 'Payment')
    status_map = {
        'active': 'paid',
        'expired': 'paid',
        'rejected': 'failed',
        'cancelled': 'cancelled',
    }
    for subscription in Subscription.objects.select_related('package').all():
        status = status_map.get(subscription.status, 'pending')
        Payment.objects.get_or_create(
            subscription=subscription,
            defaults={
                'user_id': subscription.user_id,
                'package_id': subscription.package_id,
                'amount': subscription.price_snapshot,
                'currency': subscription.package.currency,
                'status': status,
                'reference': f"BKP-{uuid4().hex[:12].upper()}",
                'paid_at': subscription.approved_at if status == 'paid' else None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_package_betslip_link_package_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='UGX', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(default=catalog.models.payment_reference, editable=False, max_length=24, unique=True)),
                ('provider', models.CharField(default='manual', max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='catalog.package')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='catalog.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(create_existing_payments, migrations.RunPython.noop),
    ]
