# Generated by Django 5.2.17 on 2026-09-21 17:15

import django.utils.timezone
from django.db import migrations, models


def copy_existing_captions(apps, schema_editor):
    RecentWin = apps.get_model('catalog', 'RecentWin')
    for win in RecentWin.objects.filter(caption=''):
        win.caption = win.summary or win.title
        win.save(update_fields=['caption'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwin',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(copy_existing_captions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recentwin',
            name='settled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recentwin',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recentwin',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
